### ISSUE TITLE
Where is typeahead-bootstrap.css?

### ISSUE THREAD

**Issue by hintham** [biggora/bootstrap-ajax-typeahead#15]
Hi Aleksej,

I have have successfully integrated your typeahead ajax plugin in my website and it's working like a charm. In the section under Bootstrap integration you mention that typeahead-bootstrap.css is required to apply the Bootstrap theme to the dropdown. I can't find any reference to this css file. Is it still required? and if so, can you point me to it's location?

I also have a question regarding the return data. If I have other fields apart from the value and display fields, how can I access those when an item is selected? Should I combine them into a single value field in the preProcess function? Or is there another way?

Regards

Ron Marinusse

**Comment by biggora** [comment]
Hi, typeahead-bootstrap.css was removed during the transition to version 3.
Now fairly standard bootstrap.css or bootstrap.min.css.
