### ISSUE TITLE
Suggest me how to get the selected Id ? 

### ISSUE THREAD

**Issue by cullsin** [biggora/bootstrap-ajax-typeahead#18]
Hi, 

Typeahead works fine for me through Ajax remote call. Can you please suggest me 
how do I get the "id" value for the final selected item ? 

$("#element").val() return the name / text . 

Raja K

**Comment by biggora** [comment]
Hi,
for manipulation to data, use the callback function "onSelect"

```js
$("input.typeahead").typeahead({
    onSelect: function(item) {
        console.log(item);
       // where { 'id' : 1, 'name' : 'Toronto' }
    },
   .....
});
```
example code https://github.com/biggora/bootstrap-ajax-typeahead#extended-usage

**Comment by cullsin** [comment]
Hi, Thank you so much :)
