### ISSUE TITLE
strange result with some word

### ISSUE THREAD

**Issue by marccollin** [biggora/bootstrap-ajax-typeahead#23]
I use twitter boostrap 3, jquery 2.1-4

$("#model").typeahead({
   source:[{modelId:1,model:"Echo"},{modelId:2,model:"Corolla"}],
   displayField: 'model',
   valueField: 'modelId'
});

![typeahead1](https://cloud.githubusercontent.com/assets/4097381/8394854/bc28182c-1d19-11e5-8009-886500918cbf.jpeg)

![typeahead2](https://cloud.githubusercontent.com/assets/4097381/8394867/276fb5e0-1d1a-11e5-90b4-5b6a943a4171.jpeg)

![typeahead3](https://cloud.githubusercontent.com/assets/4097381/8394870/2d37bfd6-1d1a-11e5-9f35-8a2b5be8d66f.jpeg)

i get strange result, i need to type many letter to start to get a result

**Comment by biggora** [comment]
Hi,
use 'triggerLength' option to specify the minimum length of text to take action on.
