### ISSUE TITLE
How can we add more data in item object recieved in onSelect ?

### ISSUE THREAD

**Issue by mukeshs-times** [biggora/bootstrap-ajax-typeahead#25]
Hello,
I want  to add more fields in item object of onSelect event. i had all fields in json response of server but  they are not coming in item object of onSelect.

**Comment by Erwane** [comment]
we do like that : 

http://pastebin.com/UsYCyUUZ

**Comment by mukeshs-times** [comment]
Thanks, i did the same. +1:
