### ISSUE TITLE
I could not make destroy and re-initialize typeahead with remote file 

### ISSUE THREAD

**Issue by mannemvamsi** [biggora/bootstrap-ajax-typeahead#28]
I have two inputs, both are initialized with typeahead(). When first input is filled-i.e: an ajax called is fired to alter the remote data file. Now I am trying to destroy typeahead for second input and re-initialize it. But this always fetches old data(probably cached). 

How do I avoid cached data for a remote json file. ?

**Comment by mannemvamsi** [comment]
Never mind. Got worked..!

**Comment by mabdelwahab** [comment]
Can you please tell me how you solved it ?
I'm facing this problem as the URL of the second typeahead depends on the selected value of the first typeahead , but I found that the URL is only initialized once.
